image:
  file: Dockerfile
ports:
  - port: 6080
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
tasks:
  - command: cd /tmp/eclipse-installer && ./eclipse-inst
