image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      cargo build
      cargo install --path . --force
    command: dockerfreeze --help
    name: Build Dockerfreeze
  - init: |
      pip3 install -r gui/requirements.txt
      python3 gui/gui.py
    name: Build GUI
ports:
  - port: 6080
    onOpen: ignore
  - port: 35900
    onOpen: ignore
  - port: 5900
    onOpen: ignore
vscode:
  extensions:
    - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==
    - Swellaby.vscode-rust-test-adapter@0.11.0:Xg+YeZZQiVpVUsIkH+uiiw==
    - serayuzgur.crates@0.4.7:HMkoguLcXp9M3ud7ac3eIw==
    - belfz.search-crates-io@1.2.1:kSLnyrOhXtYPjQpKnMr4eQ==
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==
    - timonwong.shellcheck@0.9.0:hsU/Rd39aqPYowTqL+DbXg==
    - mads-hartmann.bash-ide-vscode@1.4.0:/qx+rdXE/fGTGWhelNf3aQ==
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addComment: true
    addLabel: true
