[package]
name = "dockerfreeze"
version = "0.1.0"
authors = ["Sean Hellum <seanhellum45@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.9"
regex = "1"

[build-dependencies]
subprocess = "0.2.4"
