image:
  file: .gitpod.dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - init: pip install requests && ./mach build -r
    command: ./mach run -r -Z disable-vsync
