comment:
  layout: header, diff

coverage: 
  status:
    # set a github PR status for overall project coverage with an automatically
    # calculated coverage target
    project:
      default:
        target: auto

    # patch coverage doesn't seem very helpful
    patch:
      default:
        enabled: false
