language: java
matrix:
  include:
  - jdk: openjdk8
    env: GRADLE_PUBLISH=true
dist: xenial
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
env:
  global:
  - secure: WB/Tls8INhtq+dtQj0oTxw3sk/ojJzhjonYbIb7emPn34/pfxHSJuHAKZ+NX1LaSXRdjeNtIpfkxwyhjJ/uptlXZvYcRAvXeWN+3voaTybSYCD8A0skqD5sWNAhr9sGEKstr9S/WE40c2j5iX8XTH/DEFqaPM6n37ijlhk+qSgI=
  - secure: O4FHP2t3IiYyDEFhW3r06p+/p6ogkQ2je9l52IrBQQAUQhFrsSoSynGaDCfBnU80zWpV0KcbSLnLlftkVpDYgYtXnqyplROFSTG6lMNQnRfzZijM8r5P2bRP3cjRdft00iZO8Z3zKFStIVrtwXLaBIO/FmeMKUmVuQyqPvOnNsg=
  - secure: S5Cfjtn6SGWw9YXllWpzqt1Xl7xgetucfnZCIloRob2JWbDMc4xh5qLFXtkQm+8uFTmeXHjPaFQGoJ6s7/Tyl/J/oOpwRj6GQJ5sBHj8Gz/4cDx5oLKjss5wQj1D7RF/xGvYUh+5Ti3xbpw673FIfeW7kBmyLFNlsljZA08MhIQ=
  - secure: eOF3/fsxFxmpnKeEOtL4gurcW7P/s8IyKsKJDWglrjNAP/iA1J6RmqROdT1rogf+9njNOrrqvHOtb2oJ2dBRHCfW4UiqZbPcBS/hV1kas61ObS/oWq/iU4mf6YxWQEzshiR53DToZWployMBop/mOQOxuIGdA9Sn4XZTWyxjnZ4=
  - secure: cReuuLJS5N4lG+8YGikml2/qaiiGeD0Wq7y5midQG9ppYpfkH51W7VwVb//RgGqcTGPV/WNuogRYgbqIZC2HLqLIDG7TYbVsvI3Y16pPcXJvJEORFhItOwzapv8ahMLJSG8nwm+f6QJ5b8j+J8VvANSGvlEYuy1A8/NiRC+nH6Q=
  - secure: fDs5pE/wrYkHNPqfeE9ZNhiIlZd3bx42dHxT0PIp5kwFfOc79GtC6OXfL4lQcHV4TCja2MnTM/NbchZBvaISsJLCyku4ZArBaU0uKVi6kffzGLPcPyGZdJNF+KDiG9qgo2fXv0yV5saxF/bfkoU+PfaeS4fDK3JujQia61npXIY=
cache:
  directories:
  - "$HOME/.gradle"
