[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.35"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[prune]
  go-tests = true
  unused-packages = true
