language: java
jdk:
- oraclejdk8
sudo: false
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: FkKx7tPnSS0uG70Iv8cIsNynsA7BYbElQ2TRWpcYY4LBYfKiB2+Z/mRex8d0O92E1+ZqHIzXyAMpGy6F37sNUCrOG9ZkY8IYyx2joNHjgFqMM6dJg2XY22liBwATq5ectzqdorLY3ESGe0I6YKVum7wuRyNpVDc+wOn3SHJDrDM=
  - secure: Ew05M9oZ/hH/bdpar3ajBzef1Jeu5+HMD4weMuaVcEZyBhDcQla54gDmaxqu6/drKb/z/F+WwAw6P7ehx8R6n/8ghw9tdR2LcFo5W67rKk9S6iPOltBfT3tn8hHXLJewunK8pJ3gp4bsqFIoXKAtQFvznDv16ERa/Qa+4oWSAsk=
  - secure: aNmFi1Ai3jdjRw8h4B/TFowaigk+9nh78YAkYQ69iDi2J2PkKZvQRYu0ATQBHud1XnlQH1dKv54k8ofqGAymsMuQ7PfPXM0fEImdU0tv2QLBaINGl2TP+vjW7i02OUDQOm7Hv5F1XZHQcwh5r+34HB5j48ZSUNFOQSFIWNZIYro=
  - secure: JDzobrcViIlXdiw0hING6Wn0FgU35m7U59rikptaafOwyoAtDbLM7tkymu7rw8MeOzxSsmv8MSU5VHgqFEpAVZ5tF8WW+3IXkcMnF/6VBSwodfS5ZtN0zdOp3p2rjvTnvUlexmur6UFf7pZFAhY/X6WedBq3Yhc1MRWPjNsH4Zo=
