language: go

go:
  - 1.3

install:
  - go get github.com/coreos/etcd
  - go get github.com/coreos/go-etcd/etcd
  - go get github.com/coreos/go-log/log
  - go get github.com/miekg/dns
  - go get github.com/miekg/go-metrics
  - go get github.com/miekg/go-metrics/influxdb
  - go get github.com/miekg/go-metrics/stathat

before_script:
  - go build -o $HOME/gopath/src/github.com/coreos/etcd/etcd.run github.com/coreos/etcd
  - $HOME/gopath/src/github.com/coreos/etcd/etcd.run &
