language: scala
scala:
  - 2.10.6
  - 2.11.11
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
matrix:
  include:
  - scala: 2.12.2
    jdk: oraclejdk8
sudo: false
script:
  - sbt ++$TRAVIS_SCALA_VERSION test unidoc